webtalk_init -webtalk_dir /home/ly/Desktop/stage_IP_SVM/SVM/SVM.sim/sim_1/behav/xsim/xsim.dir/Twos_Complement_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Jul 25 12:34:08 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "25a99432-ce62-4fa3-aed9-c8e180a8cad5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "67f277647ccd43a999c8aa3a88d9ea6a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "7" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 23.04" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 5700U with Radeon Graphics" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "4106.312 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.02_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "123060_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2388004677 -regid "" -xml /home/ly/Desktop/stage_IP_SVM/SVM/SVM.sim/sim_1/behav/xsim/xsim.dir/Twos_Complement_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/ly/Desktop/stage_IP_SVM/SVM/SVM.sim/sim_1/behav/xsim/xsim.dir/Twos_Complement_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/ly/Desktop/stage_IP_SVM/SVM/SVM.sim/sim_1/behav/xsim/xsim.dir/Twos_Complement_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
