#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Tue Jul 25 12:33:10 CEST 2023
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto 67f277647ccd43a999c8aa3a88d9ea6a --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot Twos_Complement_tb_behav xil_defaultlib.Twos_Complement_tb -log elaborate.log"
xelab -wto 67f277647ccd43a999c8aa3a88d9ea6a --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot Twos_Complement_tb_behav xil_defaultlib.Twos_Complement_tb -log elaborate.log

