@echo off
REM ****************************************************************************
REM Vivado (TM) v2022.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Thu Aug 24 04:30:12 +0200 2023
REM SW Build 3671981 on Fri Oct 14 05:00:03 MDT 2022
REM
REM IP Build 3669848 on Fri Oct 14 08:30:02 MDT 2022
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim Square_Difference_tb_behav -key {Behavioral:sim_1:Functional:Square_Difference_tb} -tclbatch Square_Difference_tb.tcl -view C:/Users/liyon/Desktop/Square_Difference/Square_Difference.srcs/sim_1/imports/Square_28bits/Square_28bits_tb_behav.wcfg -log simulate.log"
call xsim  Square_Difference_tb_behav -key {Behavioral:sim_1:Functional:Square_Difference_tb} -tclbatch Square_Difference_tb.tcl -view C:/Users/liyon/Desktop/Square_Difference/Square_Difference.srcs/sim_1/imports/Square_28bits/Square_28bits_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
